### ISSUE TITLE
Link to wiki in Readme (https://github.com/swindonmakers/swindonmakers.github.com/wiki/LogoBot) gives a 404

### ISSUE THREAD

**Issue by q2dg** [snhack/LogoBot#84]
Ei, is this project alive?
Nobody answer me...

**Comment by castaway** [comment]
Yes we are alive.. however we all have jobs ;)

I've fixed that link now. It would be helpful if you would submit patches/pull requests along with your issues, thanks!

**Comment by q2dg** [comment]
I will do so!
Thanks!!
